[package]
name = "rune-factory-3-internal-trainer"
edition = "2021"
publish = false

[lib]
name = "hid"
crate-type = ["cdylib"]

[dependencies]
hudhook = { git = "https://github.com/veeenu/hudhook.git", rev = "9c78aa5", default-features = false, features = [
    "dx11",
] }
libmem = "5.0.1"
strum = "0.26.3"
strum_macros = "0.26.4"
unsafe_fn_body = "0.1.3"

[build-dependencies]
forward-dll = "0.1.16"
